# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: src/infrastructure/proto/metrics.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import src.infrastructure.proto.metrics_pb2


class MetricsServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SendMetric(self, stream: 'grpclib.server.Stream[src.infrastructure.proto.metrics_pb2.MetricRequest, src.infrastructure.proto.metrics_pb2.MetricResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/metrics.MetricsService/SendMetric': grpclib.const.Handler(
                self.SendMetric,
                grpclib.const.Cardinality.UNARY_UNARY,
                src.infrastructure.proto.metrics_pb2.MetricRequest,
                src.infrastructure.proto.metrics_pb2.MetricResponse,
            ),
        }


class MetricsServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SendMetric = grpclib.client.UnaryUnaryMethod(
            channel,
            '/metrics.MetricsService/SendMetric',
            src.infrastructure.proto.metrics_pb2.MetricRequest,
            src.infrastructure.proto.metrics_pb2.MetricResponse,
        )
