# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/infrastructure/proto/metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/infrastructure/proto/metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&src/infrastructure/proto/metrics.proto\x12\x07metrics\"\xc1\x01\n\rMetricRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x13\n\x0bmetric_type\x18\x04 \x01(\t\x12\x32\n\x06labels\x18\x05 \x03(\x0b\x32\".metrics.MetricRequest.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\x0eMetricResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\x0eMetricsService\x12=\n\nSendMetric\x12\x16.metrics.MetricRequest\x1a\x17.metrics.MetricResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.infrastructure.proto.metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_METRICREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_METRICREQUEST']._serialized_start=52
  _globals['_METRICREQUEST']._serialized_end=245
  _globals['_METRICREQUEST_LABELSENTRY']._serialized_start=200
  _globals['_METRICREQUEST_LABELSENTRY']._serialized_end=245
  _globals['_METRICRESPONSE']._serialized_start=247
  _globals['_METRICRESPONSE']._serialized_end=297
  _globals['_METRICSSERVICE']._serialized_start=299
  _globals['_METRICSSERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
